### ISSUE TITLE
Compatibility with sqlite3 v2?

### ISSUE THREAD

**Issue by airblade** [fractaledmind/activerecord-enhancedsqlite3-adapter#13]
This gem depends on sqlite3 ~> 1.6.  Is it possible to release a new version which allows using sqlite3 v2.0.x?  (Assuming they're compatible?)

**Comment by fractaledmind** [comment]
Currently, there is no point release of Rails that is compatible with v2.0.x of the `sqlite3-ruby` gem, so I can't bump this gem yet either. Rails `main` is compatible, so hopefully a point release will be made sometime relatively soon with that feature.

**Comment by fractaledmind** [comment]
But, I did realize that I can simply use `>=` instead of `~>` in my version restriction to handle both, so I just pushed version 0.7.0 with that change

**Comment by airblade** [comment]
Thank you!
