### ISSUE TITLE
Enabling isolate_connection_pools throws error.

### ISSUE THREAD

**Issue by ghaydarov** [fractaledmind/activerecord-enhancedsqlite3-adapter#22]
When enabling `config.enhanced_sqlite3.isolate_connection_pools = true`, I am getting the following error when starting rails server: `EnhancedSQLite3::Error: development has 4 configurations (EnhancedSQLite3::Error)`

This is what my application_record.rb look like.

```class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  connects_to database: { writing: :primary, reading: :primary_replica }
end
```

Any ideas on this appreciated. I am using Rails 7.1.3.4.

```21:08:27 web.1  | /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/activerecord-enhancedsqlite3-adapter-0.8.0/lib/enhanced_sqlite3/railtie.rb:49:in `block (2 levels) in <class:Railtie>': development has 4 configurations (EnhancedSQLite3::Error)
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:97:in `class_eval'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:97:in `block in execute_hook'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:77:in `each'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/base.rb:338:in `<module:ActiveRecord>'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/base.rb:15:in `<main>'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
21:08:27 web.1  | 	from /Users/dev/Desktop/webpress/app/models/application_record.rb:1:in `<main>'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:26:in `require'
21:08:27 web.1  | 	from /Users/dev/Desktop/webpress/app/models/user.rb:3:in `<main>'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:26:in `require'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/inflector/methods.rb:290:in `const_get'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/inflector/methods.rb:290:in `constantize'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/devise-4.9.4/lib/devise.rb:327:in `get'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/devise-4.9.4/lib/devise/mapping.rb:83:in `to'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/devise-4.9.4/lib/devise/mapping.rb:78:in `modules'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/devise-4.9.4/lib/devise/mapping.rb:95:in `routes'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/devise-4.9.4/lib/devise/mapping.rb:162:in `default_used_route'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/devise-4.9.4/lib/devise/mapping.rb:72:in `initialize'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/devise-4.9.4/lib/devise.rb:361:in `new'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/devise-4.9.4/lib/devise.rb:361:in `add_mapping'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/devise-4.9.4/lib/devise/rails/routes.rb:243:in `block in devise_for'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/devise-4.9.4/lib/devise/rails/routes.rb:242:in `each'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/devise-4.9.4/lib/devise/rails/routes.rb:242:in `devise_for'
21:08:27 web.1  | 	from /Users/dev/Desktop/webpress/config/routes.rb:12:in `block (2 levels) in <main>'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/routing/mapper.rb:882:in `scope'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/routing/mapper.rb:1011:in `constraints'
21:08:27 web.1  | 	from /Users/dev/Desktop/webpress/config/routes.rb:3:in `block in <main>'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/routing/route_set.rb:448:in `instance_exec'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/routing/route_set.rb:448:in `eval_block'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/routing/route_set.rb:430:in `draw'
21:08:27 web.1  | 	from /Users/dev/Desktop/webpress/config/routes.rb:1:in `<main>'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/application/routes_reloader.rb:50:in `load'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/application/routes_reloader.rb:50:in `block in load_paths'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/application/routes_reloader.rb:50:in `each'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/application/routes_reloader.rb:50:in `load_paths'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/application/routes_reloader.rb:24:in `reload!'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/application/routes_reloader.rb:38:in `block in updater'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/file_update_checker.rb:85:in `execute'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/application/routes_reloader.rb:13:in `execute'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/application/finisher.rb:161:in `block in <module:Finisher>'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:32:in `instance_exec'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:32:in `run'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/tsort.rb:350:in `each'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/tsort.rb:350:in `call'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:60:in `run_initializers'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/application.rb:426:in `initialize!'
21:08:27 web.1  | 	from /Users/dev/Desktop/webpress/config/environment.rb:5:in `<main>'
21:08:27 web.1  | 	from config.ru:3:in `require_relative'
21:08:27 web.1  | 	from config.ru:3:in `block (2 levels) in <main>'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/builder.rb:108:in `eval'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/builder.rb:108:in `new_from_string'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/builder.rb:97:in `load_file'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/builder.rb:67:in `parse_file'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/rackup-2.1.0/lib/rackup/server.rb:354:in `build_app_and_options_from_config'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/rackup-2.1.0/lib/rackup/server.rb:263:in `app'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/rackup-2.1.0/lib/rackup/server.rb:424:in `wrapped_app'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/commands/server/server_command.rb:36:in `start'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/commands/server/server_command.rb:145:in `block in perform'
21:08:27 web.1  | 	from <internal:kernel>:90:in `tap'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/commands/server/server_command.rb:136:in `perform'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/command/base.rb:178:in `invoke_command'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/command/base.rb:73:in `perform'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/command.rb:71:in `block in invoke'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/command.rb:149:in `with_argv'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/command.rb:69:in `invoke'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.1.3.4/lib/rails/commands.rb:18:in `<main>'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
21:08:27 web.1  | 	from /Users/dev/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
21:08:27 web.1  | 	from bin/rails:4:in `<main>'
21:08:27 css.1  | bin/rails aborted!
21:08:27 css.1  | EnhancedSQLite3::Error: development has 4 configurations (EnhancedSQLite3::Error)
21:08:27 css.1  | /Users/dev/Desktop/webpress/app/models/application_record.rb:1:in `<main>'
21:08:27 css.1  | /Users/dev/Desktop/webpress/app/models/user.rb:3:in `<main>'
21:08:27 css.1  | /Users/dev/Desktop/webpress/config/routes.rb:12:in `block (2 levels) in <main>'
21:08:27 css.1  | /Users/dev/Desktop/webpress/config/routes.rb:3:in `block in <main>'
21:08:27 css.1  | /Users/dev/Desktop/webpress/config/routes.rb:1:in `<main>'
21:08:27 css.1  | /Users/dev/Desktop/webpress/config/environment.rb:5:in `<main>'
21:08:27 css.1  | Tasks: TOP => tailwindcss:watch => environment
21:08:27 css.1  | (See full trace by running task with --trace)
21:08:27 css.1  | error Command failed with exit code 1.
21:08:27 css.1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:08:28 css.1  | exited with code 1
21:08:28 system | sending SIGTERM to all processes
21:08:28 web.1  | exited with code 1
21:08:28 js.1   | exited with code```

**Comment by fractaledmind** [comment]
I need to update the README with more details on the constraints to have this feature work. For a quick peak, read the code here: lib/enhanced_sqlite3/railtie.rb

The short version is that you either have one database defined in your database.yml or you need one named reader and one named writer. Otherwise, I'm not sure how to infer which to connect to. 

As you will see, I calls connects_to in the initializer. If you have thoughts on how to make this feature work while allowing you to call that yourself, I'm open to PRs

**Comment by ghaydarov** [comment]
Thank you for the response @fractaledmind . 

I read the code. I guess I have too many questions now :)

From what I understand, gem is basically doing `connects_to database: {writing: :writer, reading: :reader}` assuming we have a single database?

Then, this does not take `replicas` into account it seems.

In that case, if we have replica db also, doing `connects_to database: { writing: :primary, reading: :primary_replica }` would more less do the same thing or maybe it's more nuanced than that.

I also have this, since I have two databases for main app, which is also overridden by this config of the gem.
 
```
Rails.application.configure do
  config.active_record.database_selector = { delay: 2.seconds }
  config.active_record.database_resolver = ActiveRecord::Middleware::DatabaseSelector::Resolver
  config.active_record.database_resolver_context = ActiveRecord::Middleware::DatabaseSelector::Resolver::Session
end
```


Also, does passing `pool: 1` on the config ensure that writer keeps that connection for write only? How about rest of the pool, are those also available for writing? 

I am trying to understand, as I am not much read on the topic. 

I appreciate the work you are doing.

**Comment by fractaledmind** [comment]
If you are actually using two databases, you can't use this feature. Sorry. I may try to experiment and see if it could be made possible, but it isn't possible now. 

But this shouldn't be a major concern. This is an experimental enhancement
